name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Build
        run: make build
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Run tests
        run: make test
  testacc:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Environment
        run: make ci-build-setup
      - name: Start bitbucket server
        run: make bitbucket-start
      - name: Run acceptance tests
        run: BITBUCKET_SERVER=http://localhost:7990 BITBUCKET_USERNAME=admin BITBUCKET_PASSWORD=admin make testacc
      - name: Stop bitbucket server
        run: make bitbucket-stop
  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Format check
        run: make fmtcheck
  vet:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO 1.16.x
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Run vet
        run: make vet
